### ISSUE TITLE
모바일 데이터 베이스 Realm 도입

### ISSUE THREAD

**Issue by pr-lawrence** [bigxodus/candlelight#15]
https://realm.io/docs/swift/latest/

sqlite3나 이거 중에 선택해서 사용하면 될거 같다.

**Comment by waynejo** [comment]
저도 relam에 한표입니다!

**Comment by pr-lawrence** [comment]
http://www.appcoda.com/realm-database-swift/

**Comment by pr-lawrence** [comment]
함께 살펴보기

* nsuserdefault
* FMDB
