### ISSUE TITLE
게시판 목록 받아오기

### ISSUE THREAD

**Issue by waynejo** [bigxodus/candlelight#9]
- 각 게시판 선택시 게시물을 받아올 수 있는 공통된 API를 만들 필요가 있어 보임
 - 약 아래와 같은 형식의 API를 고려하고 있으나, 논의가 필요함
    siteUrl:String -> Future[Option[List[ContentsTitle]]]
 - ContentsTitle 객체 내의 항목 (제목, 작성자, 게시 날짜) 등의 요소에 대해 정할 필요가 있음

**Comment by pr-lawrence** [comment]
:+1:

**Comment by pr-lawrence** [comment]
아래 처럼 작성할 수 있도록 개발

```
let lists = clienParse.getList() //  최신 list를 reload

let lists - clien.getList(id) // id 이후 llist를 reload
```

```
[
  {
    "id": 123,
    "title": "[속보] 퇴근시간",
    "url": "http://www.example.com",
    "author": "wayne",
    "date": "",
    "readCount": 100
  },
  {
    ...
  }
]
```

**Comment by waynejo** [comment]
ListCrawler protocol을 상속받아서 사용하시면 됩니다!
일단 임시로 게시판 title만 나오도록 해두었습니다.
